/* 
 * Structure:
 * [Temple Lookup Name, Display Name, Points, Temple Index]
*/

export const templeMap = [
    ["Attack", "Attack", 1, 1],
    ["Defence", "Defence", 1, 2],
    // ["Strength", "Strength", 1, 3],
    // ["Hitpoints", "Hitpoints", 1, 4],
    // ["Ranged", "Ranged", 1, 5],
    // ["Magic", "Magic", 1, 7],
    // ["Woodcutting", "Woodcutting", 1, 9],
    // ["Fishing", "Fishing", 1, 11],
    // ["Firemaking", "Firemaking", 1, 12],
    // ["Mining", "Mining", 1, 15],
    // ["Agility", "Agility", 1, 17],
    // ["Thieving", "Thieving", 1, 18],
    // ["Slayer", "Slayer", 1, 19],
    // ["Runecraft", "Runecrafting", 1, 21],
    // ["Hunter", "Hunter", 1, 22],
    // ["Beginner_Clue", "Beginner Clues", 1, 26],
    // ["Easy_Clue", "Easy Clues", 1, 27],
    // ["Medium_Clue", "Medium Clues", 1, 28],
    // ["Hard_Clue", "Hard Clues", 2, 29],
    // ["Elite_Clue", "Elite Clues", 2, 30],
    // ["Master_Clue", "Master Clues", 2, 31],
    // ["Abyssal_Sire", "Sire", 2, 33],
    // ["Alchemical_Hydra", "Hydra", 1, 34],
    // ["Barrows_Chests", "Barrows", 1, 35],
    // ["Bryophyta", "Bryophyta", 1, 36],
    // ["Callisto", "Callisto", 1, 37],
    // ["Cerberus", "Cerberus", 1, 38],
    // ["Chambers_of_Xeric", "CoX", 3, 39],
    // ["Chambers_of_Xeric_Challenge_Mode", "CM", 3, 40],
    // ["Chaos_Elemental", "Chaos Elemental", 1, 41],
    // ["Chaos_Fanatic", "Chaos Fanatic", 1, 42],
    // ["Commander_Zilyana", "Zily", 2, 43],
    // ["Corporeal_Beast", "Corp", 3, 44],
    // ["Crazy_Archaeologist", "Crazy Arch", 1, 45],
    // ["Dagannoth_Prime", "Prime", 1, 46],
    // ["Dagannoth_Rex", "Rex", 1, 47],
    // ["Dagannoth_Supreme", "Supreme", 1, 48],
    // ["Deranged_Archaeologist", "Degranged Arch", 1, 49],
    // ["General_Graardor", "Graardor", 2, 50],
    // ["Giant_Mole", "Giant Mole", 1, 51],
    // ["Grotesque_Guardians", "Grotesque Guardians", 1, 52],
    // ["Hespori", "Hespori", 1, 53],
    // ["Kalphite_Queen", "KQ", 2, 54],
    // ["King_Black_Dragon", "KBD", 2, 55],
    // ["Kraken", "Kraken", 1, 56],
    // ["KreeArra", "Kree", 2, 57],
    // ["Kril_Tsutsaroth", "Kril", 2, 58],
    // ["Mimic", "Mimic", 1, 59],
    // ["Obor", "Obor", 1, 60],
    // ["Sarachnis", "Sarachnis", 1, 61],
    // ["Scorpia", "Scorpia", 1, 62],
    // ["Skotizo", "Skotizo", 1, 63],
    // ["The_Gauntlet", "Gauntlet", 1, 64],
    // ["The_Corrupted_Gauntlet", "CG", 2, 65],
    // ["Theatre_of_Blood", "ToB", 3, 66],
    // ["Thermonuclear_Smoke_Devil", "Thermy", 1, 67],
    // ["TzKal-Zuk", "TzKal-Zuk", 3, 68],
    // ["TzTok-Jad", "TzTok-Jad", 2, 69],
    // ["Venenatis", "Venenatis", 1, 70],
    // ["Vetion", "Vetion", 1, 71],
    // ["Vorkath", "Vorkath", 2, 72],
    // ["Wintertodt", "Wintertodt", 1, 73],
    // ["Zalcano", "Zalcano", 1, 74],
    // ["Zulrah", "Zulrah", 2, 75],
    // ["The_Nightmare", "Nightmare", 2, 82],
    // ["Tempoross", "Tempoross", 1, 84],
    // ["Theatre_of_Blood_Challenge_Mode", "HMT ToB", 3, 85],
    // ["Phosani's_Nightmare", "PNM", 3, 88],
    // ["Nex", "Nex", 2, 89],
    // ["Rift", "Rift", 1, 90],
    // ["Tombs_of_Amascut", "ToA", 2, 93],
    // ["Tombs_of_Amascut_Expert", "Expert ToA", 3, 94],
    // ["Phantom_Muspah", "Phantom Muspah", 2, 95],
    // ["Artio", "Artio", 1, 96],
    // ["Calvarion", "Calvarion", 1, 97],
    // ["Spindel", "Spindel", 1, 98],
    // ["Duke_Sucellus", "Duke", 2, 100],
    // ["The_Leviathan", "Leviathan", 2, 101],
    // ["The_Whisperer", "Whisperer", 2, 102],
    // ["Vardorvis", "Vardorvis", 2, 103],
    // ["Scurrius", "Scurrius", 1, 104],
    // ["Lunar_Chests", "Moons Of Peril", 2, 106],
    // ["Sol_Heredit", "Colosseum", 3, 107],
];
